### 자료구조
1. 리스트 (기본 구조) >> [1,2]
2. 튜플 (상수, 불변) >> (1,2)
3. 딕셔너리(key : value) >> {1:'apple', 2:'orange'}
4. 세트 (set) >> 집합
5. 배열 (numpy)
6. 판다스 구조 (Series, DataFrame)
----

### 넘파이 (numpy)
- 열(array) 생성, 연산
- 나의 데이터 타입 허용 (int, float, ... ), 다차원 자료구조



In [1]:
#1차원 배열
import numpy as np
np.array([1,2,3])

array([1, 2, 3])

In [4]:
#2차원 배열
np.array([[1,2,3],[4,5,6],[7,8,9]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
#3차원 배열
np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [5]:
np.arange(1,26)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25])

In [7]:
np.arange(1,26).reshape(5,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [10]:
# 색인
a1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
a1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
# array[ 행 선택, 열선 택]
# 정수 색인 >> 차원 축소 발생
a1[1,:]

array([4, 5, 6])

In [13]:
a1[:,1]

array([2, 5, 8])

In [15]:
# 슬라이스 색인 >> 차원 축소 발생 x
a1[:,1:2]

array([[2],
       [5],
       [8]])