In [1]:
import numpy as np

x = np.array([1,2,3])
print(x)

[1 2 3]


In [2]:
# 크기가 (1,3) 인 2차원
np.array([[1,2,3]])

array([[1, 2, 3]])

In [3]:
# 크기가 (1,3)인 2차원 열벡터
np.array([[1],[2],[3]])

array([[1],
       [2],
       [3]])

In [4]:
from scipy import linalg
s = np.array([2,3,1])

In [5]:
# 단위 벡터

s / linalg.norm(s)

array([0.53452248, 0.80178373, 0.26726124])

In [7]:
# norm
x = np.array([1,-3])
x / linalg.norm(x)

array([ 0.31622777, -0.9486833 ])

In [8]:
# norm 2
x / (x**2).sum()**0.5

array([ 0.31622777, -0.9486833 ])

In [9]:
np.zeros(5) # 실수로 반환

array([0., 0., 0., 0., 0.])

In [10]:
np.zeros(5).shape

(5,)

In [11]:
s=(2,2)
np.zeros(s)

array([[0., 0.],
       [0., 0.]])

In [12]:
# 선형 독립 ,선형 종속
#rank

# matrix_rank()

x = np.array([[2,7],[5,1]])
np.linalg.matrix_rank(x)

2

In [14]:
x_2 = np.array([[2,4],[3,6]])
np.linalg.matrix_rank(x_2)

1

In [22]:
# 벡터의 내적과 외적

x = [2,3]
y = [3,1]

#벡터의 내적 (zip 함수 활용)

z = [i*j for i,j in zip(x,y)]
print(z)

[6, 3]


In [21]:
z = [i-j for i,j in zip(x,y)]
print(z)

[-1, 2]


In [16]:
# zip 함수

list(zip([1,2,3],[4,5,6]))

[(1, 4), (2, 5), (3, 6)]

In [17]:
list(zip([1,2,3],[4,5,6],[7,8,9]))

[(1, 4, 7), (2, 5, 8), (3, 6, 9)]